name: VaultChatFormatter
version: '1.0-SNAPSHOT'
main: me.lucko.chatformatter.VaultChatFormatter
depend: [Vault]
api-version: 1.21
load: STARTUP

commands:
  vaultchatformatter:
    description: Reload the configuration
    permission: vaultchatformatter.reload
    usage: "Did you mean to run '/vaultchatformatter reload'?"